### ISSUE TITLE
error: dot could not be found on host 1.0.0.127.in-addr.arpa (tutorial_3_first_steps.py)

### ISSUE THREAD

**Issue by cinvro** [miykael/nipype-beginner-s-guide#4]
When I tried to run the script, it gives the error:

IOError: dot could not be found on host 1.0.0.127.in-addr.arpa
Interface CommandLine failed to run.

I have everything configured as stated in the website.

**Comment by cinvro** [comment]
When I tried to run the script, it gives the error:

IOError: dot could not be found on host 1.0.0.127.in-addr.arpa
Interface CommandLine failed to run. 

I have everything configured as stated in the website.

**Comment by miykael** [comment]
This is caused by the [line 112](https://github.com/miykael/nipype-beginner-s-guide/blob/master/scripts/tutorial_3_first_steps.py#L122). The ``write_graph`` function needs a software called ``graphviz``. (I've described how to install it [here](http://miykael.github.io/nipype-beginner-s-guide/installation.html?highlight=graphviz#install-nipype-and-other-python-dependencies)).

What does it say if you type the following command into python? ``import pygraphviz``
And what does it say if you type ``dot -V`` into a normal linux terminal window?
